name: conex
channels:
  - pytorch
  - conda-forge
  - defaults
dependencies:
  - _libgcc_mutex=0.1=main
  - blas=1.0=mkl
  - ca-certificates=2020.6.20=hecda079_0
  - certifi=2020.6.20=py36h9f0ad1d_0
  - cudatoolkit=10.2.89=hfd86e86_1
  - freetype=2.10.2=h5ab3b9f_0
  - intel-openmp=2020.1=217
  - joblib=0.16.0=py_0
  - jpeg=9b=h024ee3a_2
  - ld_impl_linux-64=2.33.1=h53a641e_7
  - libedit=3.1.20191231=h7b6447c_0
  - libffi=3.3=he6710b0_2
  - libgcc-ng=9.1.0=hdf63c60_0
  - libgfortran-ng=7.3.0=hdf63c60_0
  - libpng=1.6.37=hbc83047_0
  - libstdcxx-ng=9.1.0=hdf63c60_0
  - libtiff=4.1.0=h2733197_1
  - lz4-c=1.9.2=he6710b0_0
  - mkl=2020.1=217
  - mkl-service=2.3.0=py36he904b0f_0
  - mkl_fft=1.1.0=py36h23d657b_0
  - mkl_random=1.1.1=py36h0573a6f_0
  - ncurses=6.2=he6710b0_1
  - ninja=1.9.0=py36hfd86e86_0
  - numpy=1.18.5=py36ha1c710e_0
  - numpy-base=1.18.5=py36hde5b4d6_0
  - olefile=0.46=py36_0
  - openssl=1.1.1g=h516909a_1
  - pillow=7.1.2=py36hb39fc2d_0
  - pip=20.1.1=py36_1
  - python=3.6.10=h7579374_2
  - python_abi=3.6=1_cp36m
  - pytorch=1.5.1=py3.6_cuda10.2.89_cudnn7.6.5_0
  - quaternion=2020.9.5.14.42.2=py36h68bb277_0
  - readline=8.0=h7b6447c_0
  - scikit-learn=0.23.1=py36h423224d_0
  - scipy=1.5.0=py36h0b6359f_0
  - setuptools=47.3.1=py36_0
  - six=1.15.0=py_0
  - sqlite=3.32.3=h62c20be_0
  - threadpoolctl=2.1.0=pyh5ca1d4c_0
  - tk=8.6.10=hbc83047_0
  - torchvision=0.6.1=py36_cu102
  - wheel=0.34.2=py36_0
  - xz=5.2.5=h7b6447c_0
  - zlib=1.2.11=h7b6447c_3
  - zstd=1.4.4=h0b5b093_3
  - pip:
    - absl-py==0.9.0
    - argon2-cffi==20.1.0
    - astor==0.8.1
    - attrs==20.2.0
    - backcall==0.2.0
    - bleach==3.1.5
    - cffi==1.14.2
    - cycler==0.10.0
    - decorator==4.4.2
    - defusedxml==0.6.0
    - entrypoints==0.3
    - gast==0.2.2
    - google-pasta==0.2.0
    - grpcio==1.32.0
    - h5py==2.10.0
    - importlib-metadata==1.7.0
    - ipykernel==5.3.4
    - ipython==7.16.1
    - ipython-genutils==0.2.0
    - ipywidgets==7.5.1
    - jax==0.1.72
    - jaxlib==0.1.51
    - jedi==0.17.2
    - jinja2==2.11.2
    - jsonschema==3.2.0
    - jupyter==1.0.0
    - jupyter-client==6.1.7
    - jupyter-console==6.2.0
    - jupyter-core==4.6.3
    - keras-applications==1.0.8
    - keras-preprocessing==1.1.2
    - kiwisolver==1.2.0
    - markdown==3.3
    - markupsafe==1.1.1
    - matplotlib==3.3.0
    - mistune==0.8.4
    - nbconvert==5.6.1
    - nbformat==5.0.7
    - notebook==6.1.4
    - opt-einsum==3.3.0
    - packaging==20.4
    - pandas==1.0.5
    - pandocfilters==1.4.2
    - parso==0.7.1
    - pexpect==4.8.0
    - pickleshare==0.7.5
    - prometheus-client==0.8.0
    - prompt-toolkit==3.0.7
    - protobuf==3.13.0
    - ptyprocess==0.6.0
    - pycparser==2.20
    - pygments==2.6.1
    - pyparsing==2.4.7
    - pyrsistent==0.16.0
    - python-dateutil==2.8.1
    - pytz==2020.1
    - pyzmq==19.0.2
    - qtconsole==4.7.7
    - qtpy==1.9.0
    - send2trash==1.5.0
    - tensorboard==1.15.0
    - tensorflow-estimator==1.15.1
    - tensorflow-gpu==1.15.4
    - termcolor==1.1.0
    - terminado==0.8.3
    - testpath==0.4.4
    - tornado==6.0.4
    - traitlets==4.3.3
    - wcwidth==0.2.5
    - webencodings==0.5.1
    - werkzeug==1.0.1
    - widgetsnbextension==3.5.1
    - wrapt==1.12.1
    - zipp==3.1.0
prefix: /home/cdemir/anaconda3/envs/conex

